### ISSUE TITLE
Create batch mint and batch redeem contract for set token

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#247]
Since it is very expensive and cumbersome to mint & redeem a set token with multiple components, we would like to create a contract to handle batch minting and batch redeeming of the HYSI token. 

A BatchMintable and BatchRedeemable contract should be created similar to the one found here: https://github.com/popcorndao/scaling-eth-hackathon/blob/master/packages/hardhat/contracts/BatchWithdrawablePool.sol
and incorporated into a "frontend" contract for batch minting and redeeming the HYSI set token. 

The contract functions will include:
1. receiving 3crv tokens (and calculating the amount of curve LP tokens that can be minted)
2. depositing 3crv tokens in the respective curve pools for each component of the set
3. depositing curve LP tokens into the corresponding yearn vault of the set
4. collateralizing/minting the set token with the yearn LP tokens
5. batch minting/redeeming (after amount or time threshold is met)

**Comment by RedVeil** [comment]
https://github.com/popcorndao/workspace/pull/265

**Comment by anthonymartin** [comment]
@RedVeil looking good. left some comments

**Comment by RedVeil** [comment]
Updated with simpler Batch Struct, addressed comments and batch reedeming that swaps into 3crv

**Comment by anthonymartin** [comment]
@ecmendenhall can you take a look at this PR when you have a chance?

**Comment by RedVeil** [comment]
Ok the contract works now but im certainly not happy with it.
Since we have a lot of multiplications of BigNumbers i need to divide them again to prevent overflow. This leads to some inprecise caulculations which fluctate slightly. Therefore this introduces 3 failing tests in the network test and 2 in the normal test in which the expected value changes between 2 possible outcomes. This differences are only in the gwei amounts but means that the tests are not deterministic anymore.
It also means that i need to mint 0.3% less hysi than we could with a more precise calculation. 

If someone has an idea how to multiply a bunch of bigNumbers without any loss of accuracy id be happy to change this as it would hopefully eliminate these non deterministic tests and make the contract cleaner.

(I did check the BMI implementation but they dont do any of these calculations in the contract which is why i couldnt take their approach)
