### ISSUE TITLE
redeemUnclaimedDeposits

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#357]
adds unclaimed HYSI token to redemption batch

`redeemUnclaimedDeposits(bytes32[] batchId, uint256[] amountInHYSI)`
* background:
  * It is not necessary for a user to actually claim the deposit from the batch HYSI deposit/withdrawal contract. On the frontend we should still be able to display to the user the value of their deposit regardless of whether they claimed the deposit or not. Since this is the case, when a user wants to make a withdrawal, it may be possible that their assets are still unclaimed in the contract, so this function should move the unclaimed HYSI tokens to the batch withdrawal queue. 
* specifications
  * this function should move unclaimed HYSI tokens to the batch withdrawal queue

**Comment by RedVeil** [comment]
PR https://github.com/popcorndao/workspace/pull/403

**Comment by RedVeil** [comment]
moveUnclaimedDepositsIntoCurrentBatch() allows a user to specify up to 20 processed but unclaimed batches to move their funds into a new redeem/mint batch without the need to claim all these funds before.

moveUnclaimedDepositsIntoCurrentBatch() takes an array of batchIds, an array of shares and a batchType.

    The batchIds specify where the funds get moved from.

    Shares is an array that has to align with batchIds and specifies how many token should be moved from each of the batches.
    (We dont just take all token in case someone wants to claim some of their funds and process some others)

    BatchType is important to specify if we move funds from a minting or redeeming batch. The BatchType here corresponds to the BatchType of the batches where the funds get moved from.
    (If a user wants to move 3crv from previous redeemBatches and mint HYSI with them they would use BatchType.Redeem)

Its all tested locally and with a network test (one test fails occasionally since we divide an uneven amount).

This PR also brings BatchTypes for batches with now allows to distinguish the different batches and should allow for easier queries and display from the frontend.
