### ISSUE TITLE
replace ownable with owned

### ISSUE THREAD

**Issue by anthonymartin** [popcorndao/workspace#46]
https://github.com/Synthetixio/synthetix/blob/master/contracts/Owned.sol

Affected contracts: RewardsManager, BeneficiaryVaults

**Comment by RedVeil** [comment]
done in https://github.com/popcorndao/workspace/pull/103

**Comment by RedVeil** [comment]
Before transferring ownership of any contract, the target address must accept ownership in order to effectuate the ownership transfer. If the target address does not accept ownership, then the previous contract owner will remain as the owner.

This affects contracts which use the following modifiers:
onlyCouncil
onlyGovernance
onlyOwner
